export interface DisplayData {
  gesture: string
  emoji: string
  english: string
  hindi: string
}

const DISPLAY_MAP: Record<string, DisplayData> = {
  "Dog": { gesture: "Dog", emoji: "🐕", english: "Dog", hindi: "कुत्ता" },
  "Religion": { gesture: "Religion", emoji: "🕌", english: "Religion", hindi: "धर्म" },
  "loud": { gesture: "loud", emoji: "🔊", english: "loud", hindi: "जोर से" },
  "Energy": { gesture: "Energy", emoji: "🤙", english: "Energy", hindi: "Energy" },
  "Mean": { gesture: "Mean", emoji: "🤙", english: "Mean", hindi: "Mean" },
  "Plane": { gesture: "Plane", emoji: "🤙", english: "Plane", hindi: "Plane" },
  "Car": { gesture: "Car", emoji: "🚗", english: "Car", hindi: "गाड़ी" },
  "War": { gesture: "War", emoji: "⚔️", english: "War", hindi: "युद्ध" },
  "rich": { gesture: "rich", emoji: "💰", english: "rich", hindi: "अमीर" },
  "Peace": { gesture: "Peace", emoji: "🕊️", english: "Peace", hindi: "शांति" },
  "Truck": { gesture: "Truck", emoji: "🚚", english: "Truck", hindi: "ट्रक" },
  "poor": { gesture: "poor", emoji: "🪙", english: "poor", hindi: "गरीब" },
  "Attack": { gesture: "Attack", emoji: "🤙", english: "Attack", hindi: "Attack" },
  "Bicycle": { gesture: "Bicycle", emoji: "🚲", english: "Bicycle", hindi: "साइकिल" },
  "thick": { gesture: "thick", emoji: "📗", english: "thick", hindi: "मोटा" },
  "Bus": { gesture: "Bus", emoji: "🚌", english: "Bus", hindi: "बस" },
  "Election": { gesture: "Election", emoji: "🤙", english: "Election", hindi: "Election" },
  "Boat": { gesture: "Boat", emoji: "🤙", english: "Boat", hindi: "Boat" },
  "Newspaper": { gesture: "Newspaper", emoji: "🤙", english: "Newspaper", hindi: "Newspaper" },
  "expensive": { gesture: "expensive", emoji: "💎", english: "expensive", hindi: "महंगा" },
  "Gun": { gesture: "Gun", emoji: "🤙", english: "Gun", hindi: "Gun" },
  "cheap": { gesture: "cheap", emoji: "🏷️", english: "cheap", hindi: "सस्ता" },
  "train ticket": { gesture: "train ticket", emoji: "🤙", english: "train ticket", hindi: "train ticket" },
  "Sport": { gesture: "Sport", emoji: "🤙", english: "Sport", hindi: "Sport" },
  "Transportation": { gesture: "Transportation", emoji: "🤙", english: "Transportation", hindi: "Transportation" },
  "flat": { gesture: "flat", emoji: "➖", english: "flat", hindi: "समतल" },
  "City": { gesture: "City", emoji: "🏙️", english: "City", hindi: "शहर" },
  "Exercise": { gesture: "Exercise", emoji: "🤙", english: "Exercise", hindi: "Exercise" },
  "curved": { gesture: "curved", emoji: "〰️", english: "curved", hindi: "घुमावदार" },
  "Ball": { gesture: "Ball", emoji: "🤙", english: "Ball", hindi: "Ball" },
  "House": { gesture: "House", emoji: "🏠", english: "House", hindi: "घर" },
  "male": { gesture: "male", emoji: "🤙", english: "male", hindi: "male" },
  "Cat": { gesture: "Cat", emoji: "🐈", english: "Cat", hindi: "बिल्ली" },
  "Death": { gesture: "Death", emoji: "⚰️", english: "Death", hindi: "मौत" },
  "quiet": { gesture: "quiet", emoji: "🤫", english: "quiet", hindi: "शांत" },
  "Price": { gesture: "Price", emoji: "🤙", english: "Price", hindi: "Price" },
  "Street or Road": { gesture: "Street or Road", emoji: "🤙", english: "Street or Road", hindi: "Street or Road" },
  "female": { gesture: "female", emoji: "🤙", english: "female", hindi: "female" },
  "Sign": { gesture: "Sign", emoji: "🧏", english: "Sign", hindi: "संकेत" },
  "Train Station": { gesture: "Train Station", emoji: "🤙", english: "Train Station", hindi: "Train Station" },
  "tight": { gesture: "tight", emoji: "🤏", english: "tight", hindi: "तंग" },
  "Restaurant": { gesture: "Restaurant", emoji: "🤙", english: "Restaurant", hindi: "Restaurant" },
  "Science": { gesture: "Science", emoji: "🔬", english: "Science", hindi: "विज्ञान" },
  "loose": { gesture: "loose", emoji: "👐", english: "loose", hindi: "ढीला" },
  "Court": { gesture: "Court", emoji: "🤙", english: "Court", hindi: "Court" },
  "God": { gesture: "God", emoji: "🛐", english: "God", hindi: "भगवान" },
  "high": { gesture: "high", emoji: "⬆️", english: "high", hindi: "ऊँचा" },
  "School": { gesture: "School", emoji: "🏫", english: "School", hindi: "विद्यालय" },
  "Table": { gesture: "Table", emoji: "🤙", english: "Table", hindi: "Table" },
  "low": { gesture: "low", emoji: "⬇️", english: "low", hindi: "नीचा" },
  "Chair": { gesture: "Chair", emoji: "🤙", english: "Chair", hindi: "Chair" },
  "Office": { gesture: "Office", emoji: "🤙", english: "Office", hindi: "Office" },
  "soft": { gesture: "soft", emoji: "☁️", english: "soft", hindi: "मुलायम" },
  "Bed": { gesture: "Bed", emoji: "🤙", english: "Bed", hindi: "Bed" },
  "University": { gesture: "University", emoji: "🤙", english: "University", hindi: "University" },
  "hard": { gesture: "hard", emoji: "🧱", english: "hard", hindi: "कठोर" },
  "Dream": { gesture: "Dream", emoji: "💭", english: "Dream", hindi: "सपना" },
  "Park": { gesture: "Park", emoji: "🤙", english: "Park", hindi: "Park" },
  "deep": { gesture: "deep", emoji: "🕳️", english: "deep", hindi: "गहरा" },
  "Store or Shop": { gesture: "Store or Shop", emoji: "🤙", english: "Store or Shop", hindi: "Store or Shop" },
  "Window": { gesture: "Window", emoji: "🤙", english: "Window", hindi: "Window" },
  "shallow": { gesture: "shallow", emoji: "🌊", english: "shallow", hindi: "उथला" },
  "Door": { gesture: "Door", emoji: "🤙", english: "Door", hindi: "Door" },
  "Library": { gesture: "Library", emoji: "🤙", english: "Library", hindi: "Library" },
  "clean": { gesture: "clean", emoji: "✨", english: "clean", hindi: "साफ" },
  "Fish": { gesture: "Fish", emoji: "🐟", english: "Fish", hindi: "मछली" },
  "Medicine": { gesture: "Medicine", emoji: "💊", english: "Medicine", hindi: "दवा" },
  "happy": { gesture: "happy", emoji: "😃", english: "happy", hindi: "प्रसन्न" },
  "Bedroom": { gesture: "Bedroom", emoji: "🤙", english: "Bedroom", hindi: "Bedroom" },
  "Hospital": { gesture: "Hospital", emoji: "🏥", english: "Hospital", hindi: "अस्पताल" },
  "dirty": { gesture: "dirty", emoji: "💩", english: "dirty", hindi: "गंदा" },
  "Kitchen": { gesture: "Kitchen", emoji: "🤙", english: "Kitchen", hindi: "Kitchen" },
  "Temple": { gesture: "Temple", emoji: "🤙", english: "Temple", hindi: "Temple" },
  "strong": { gesture: "strong", emoji: "🤙", english: "strong", hindi: "strong" },
  "Bathroom": { gesture: "Bathroom", emoji: "🤙", english: "Bathroom", hindi: "Bathroom" },
  "Market": { gesture: "Market", emoji: "🤙", english: "Market", hindi: "Market" },
  "weak": { gesture: "weak", emoji: "🤙", english: "weak", hindi: "weak" },
  "India": { gesture: "India", emoji: "🇮🇳", english: "India", hindi: "भारत" },
  "Pencil": { gesture: "Pencil", emoji: "🤙", english: "Pencil", hindi: "Pencil" },
  "dead": { gesture: "dead", emoji: "💀", english: "dead", hindi: "मृत" },
  "Ground": { gesture: "Ground", emoji: "🤙", english: "Ground", hindi: "Ground" },
  "Pen": { gesture: "Pen", emoji: "🤙", english: "Pen", hindi: "Pen" },
  "alive": { gesture: "alive", emoji: "🌱", english: "alive", hindi: "जीवित" },
  "Bank": { gesture: "Bank", emoji: "🤙", english: "Bank", hindi: "Bank" },
  "Photograph": { gesture: "Photograph", emoji: "🤙", english: "Photograph", hindi: "Photograph" },
  "heavy": { gesture: "heavy", emoji: "🏋️", english: "heavy", hindi: "भारी" },
  "Location": { gesture: "Location", emoji: "📍", english: "Location", hindi: "स्थान" },
  "Soap": { gesture: "Soap", emoji: "🤙", english: "Soap", hindi: "Soap" },
  "light": { gesture: "light", emoji: "🎈", english: "light", hindi: "हल्का" },
  "Book": { gesture: "Book", emoji: "📖", english: "Book", hindi: "किताब" },
  "Hat": { gesture: "Hat", emoji: "🤙", english: "Hat", hindi: "Hat" },
  "Dress": { gesture: "Dress", emoji: "🤙", english: "Dress", hindi: "Dress" },
  "Page": { gesture: "Page", emoji: "🤙", english: "Page", hindi: "Page" },
  "Key": { gesture: "Key", emoji: "🤙", english: "Key", hindi: "Key" },
  "Suit": { gesture: "Suit", emoji: "🤙", english: "Suit", hindi: "Suit" },
  "famous": { gesture: "famous", emoji: "🤙", english: "famous", hindi: "famous" },
  "Bird": { gesture: "Bird", emoji: "🐦", english: "Bird", hindi: "पक्षी" },
  "Money": { gesture: "Money", emoji: "💰", english: "Money", hindi: "पैसा" },
  "sad": { gesture: "sad", emoji: "😞", english: "sad", hindi: "उदास" },
  "I": { gesture: "I", emoji: "🙋", english: "I", hindi: "मैं" },
  "Paint": { gesture: "Paint", emoji: "🤙", english: "Paint", hindi: "Paint" },
  "Skirt": { gesture: "Skirt", emoji: "🤙", english: "Skirt", hindi: "Skirt" },
  "Letter": { gesture: "Letter", emoji: "🤙", english: "Letter", hindi: "Letter" },
  "Shirt": { gesture: "Shirt", emoji: "🤙", english: "Shirt", hindi: "Shirt" },
  "you": { gesture: "you", emoji: "🫵", english: "you", hindi: "तुम" },
  "Paper": { gesture: "Paper", emoji: "🤙", english: "Paper", hindi: "Paper" },
  "T-Shirt": { gesture: "T-Shirt", emoji: "🤙", english: "T-Shirt", hindi: "T-Shirt" },
  "he": { gesture: "he", emoji: "👨", english: "he", hindi: "वह (पुल्लिंग)" },
  "Lock": { gesture: "Lock", emoji: "🤙", english: "Lock", hindi: "Lock" },
  "Pant": { gesture: "Pant", emoji: "🤙", english: "Pant", hindi: "Pant" },
  "she": { gesture: "she", emoji: "👩", english: "she", hindi: "वह (स्त्रीलिंग)" },
  "Shoes": { gesture: "Shoes", emoji: "🤙", english: "Shoes", hindi: "Shoes" },
  "Telephone": { gesture: "Telephone", emoji: "🤙", english: "Telephone", hindi: "Telephone" },
  "it": { gesture: "it", emoji: "📦", english: "it", hindi: "यह" },
  "Bag": { gesture: "Bag", emoji: "🤙", english: "Bag", hindi: "Bag" },
  "Pocket": { gesture: "Pocket", emoji: "🤙", english: "Pocket", hindi: "Pocket" },
  "we": { gesture: "we", emoji: "🫂", english: "we", hindi: "हम" },
  "Box": { gesture: "Box", emoji: "🤙", english: "Box", hindi: "Box" },
  "Clothing": { gesture: "Clothing", emoji: "🤙", english: "Clothing", hindi: "Clothing" },
  "you (plural)": { gesture: "you (plural)", emoji: "🤙", english: "you (plural)", hindi: "you (plural)" },
  "Gift": { gesture: "Gift", emoji: "🤙", english: "Gift", hindi: "Gift" },
  "Red": { gesture: "Red", emoji: "🔴", english: "Red", hindi: "लाल" },
  "they": { gesture: "they", emoji: "👥", english: "they", hindi: "वे" },
  "Card": { gesture: "Card", emoji: "🤙", english: "Card", hindi: "Card" },
  "Green": { gesture: "Green", emoji: "🟢", english: "Green", hindi: "हरा" },
  "Hello": { gesture: "Hello", emoji: "👋", english: "Hello", hindi: "नमस्ते" },
  "Blue": { gesture: "Blue", emoji: "🔵", english: "Blue", hindi: "नीला" },
  "How are you": { gesture: "How are you", emoji: "🤔", english: "How are you", hindi: "आप कैसे हैं?" },
  "Ring": { gesture: "Ring", emoji: "🤙", english: "Ring", hindi: "Ring" },
  "Beautiful": { gesture: "Beautiful", emoji: "✨", english: "Beautiful", hindi: "सुंदर" },
  "Bill": { gesture: "Bill", emoji: "🤙", english: "Bill", hindi: "Bill" },
  "Cow": { gesture: "Cow", emoji: "🐄", english: "Cow", hindi: "गाय" },
  "Alright": { gesture: "Alright", emoji: "🤙", english: "Alright", hindi: "Alright" },
  "Tool": { gesture: "Tool", emoji: "🤙", english: "Tool", hindi: "Tool" },
  "Yellow": { gesture: "Yellow", emoji: "🟡", english: "Yellow", hindi: "पीला" },
  "Brown": { gesture: "Brown", emoji: "🟤", english: "Brown", hindi: "भूरा" },
  "Clock": { gesture: "Clock", emoji: "🤙", english: "Clock", hindi: "Clock" },
  "Good Morning": { gesture: "Good Morning", emoji: "🌅", english: "Good Morning", hindi: "सुप्रभात" },
  "Good afternoon": { gesture: "Good afternoon", emoji: "☀️", english: "Good afternoon", hindi: "शुभ दोपहर" },
  "Lamp": { gesture: "Lamp", emoji: "🤙", english: "Lamp", hindi: "Lamp" },
  "Pink": { gesture: "Pink", emoji: "🩷", english: "Pink", hindi: "गुलाबी" },
  "Fan": { gesture: "Fan", emoji: "🤙", english: "Fan", hindi: "Fan" },
  "Good evening": { gesture: "Good evening", emoji: "🌇", english: "Good evening", hindi: "शुभ संध्या" },
  "Orange": { gesture: "Orange", emoji: "🟠", english: "Orange", hindi: "नारंगी" },
  "Black": { gesture: "Black", emoji: "⚫", english: "Black", hindi: "काला" },
  "Cell phone": { gesture: "Cell phone", emoji: "🤙", english: "Cell phone", hindi: "Cell phone" },
  "Good night": { gesture: "Good night", emoji: "🌙", english: "Good night", hindi: "शुभ रात्रि" },
  "Computer": { gesture: "Computer", emoji: "💻", english: "Computer", hindi: "कंप्यूटर" },
  "Thank you": { gesture: "Thank you", emoji: "🙏", english: "Thank you", hindi: "धन्यवाद" },
  "White": { gesture: "White", emoji: "⚪", english: "White", hindi: "सफेद" },
  "Grey": { gesture: "Grey", emoji: "🔘", english: "Grey", hindi: "स्लेटी" },
  "Laptop": { gesture: "Laptop", emoji: "🤙", english: "Laptop", hindi: "Laptop" },
  "Pleased": { gesture: "Pleased", emoji: "🤙", english: "Pleased", hindi: "Pleased" },
  "Colour": { gesture: "Colour", emoji: "🎨", english: "Colour", hindi: "रंग" },
  "Screen": { gesture: "Screen", emoji: "🤙", english: "Screen", hindi: "Screen" },
  "Camera": { gesture: "Camera", emoji: "🤙", english: "Camera", hindi: "Camera" },
  "Son": { gesture: "Son", emoji: "🤙", english: "Son", hindi: "Son" },
  "Daughter": { gesture: "Daughter", emoji: "🤙", english: "Daughter", hindi: "Daughter" },
  "Television": { gesture: "Television", emoji: "🤙", english: "Television", hindi: "Television" },
  "Marriage": { gesture: "Marriage", emoji: "💍", english: "Marriage", hindi: "शादी" },
  "Mouse": { gesture: "Mouse", emoji: "🤙", english: "Mouse", hindi: "Mouse" },
  "Ugly": { gesture: "Ugly", emoji: "🙈", english: "Ugly", hindi: "बदसूरत" },
  "Mother": { gesture: "Mother", emoji: "👩", english: "Mother", hindi: "माँ" },
  "Radio": { gesture: "Radio", emoji: "🤙", english: "Radio", hindi: "Radio" },
  "Father": { gesture: "Father", emoji: "👨", english: "Father", hindi: "पिता" },
  "Summer": { gesture: "Summer", emoji: "☀️", english: "Summer", hindi: "गर्मी" },
  "Parent": { gesture: "Parent", emoji: "🤙", english: "Parent", hindi: "Parent" },
  "Spring": { gesture: "Spring", emoji: "🌸", english: "Spring", hindi: "वसंत" },
  "Baby": { gesture: "Baby", emoji: "👶", english: "Baby", hindi: "बच्चा" },
  "Winter": { gesture: "Winter", emoji: "❄️", english: "Winter", hindi: "सर्दी" },
  "Fall": { gesture: "Fall", emoji: "🍂", english: "Fall", hindi: "पतझड़" },
  "Man": { gesture: "Man", emoji: "👨", english: "Man", hindi: "आदमी" },
  "Season": { gesture: "Season", emoji: "🤙", english: "Season", hindi: "Season" },
  "Woman": { gesture: "Woman", emoji: "👩", english: "Woman", hindi: "औरत" },
  "Brother": { gesture: "Brother", emoji: "👦", english: "Brother", hindi: "भाई" },
  "Sunday": { gesture: "Sunday", emoji: "📅", english: "Sunday", hindi: "रविवार" },
  "Monday": { gesture: "Monday", emoji: "📅", english: "Monday", hindi: "सोमवार" },
  "Sister": { gesture: "Sister", emoji: "👧", english: "Sister", hindi: "बहन" },
  "Family": { gesture: "Family", emoji: "👪", english: "Family", hindi: "परिवार" },
  "Tuesday": { gesture: "Tuesday", emoji: "📅", english: "Tuesday", hindi: "मंगलवार" },
  "Grandfather": { gesture: "Grandfather", emoji: "🤙", english: "Grandfather", hindi: "Grandfather" },
  "Wednesday": { gesture: "Wednesday", emoji: "📅", english: "Wednesday", hindi: "बुधवार" },
  "Deaf": { gesture: "Deaf", emoji: "🧏", english: "Deaf", hindi: "बधिर" },
  "Horse": { gesture: "Horse", emoji: "🐎", english: "Horse", hindi: "घोड़ा" },
  "Team": { gesture: "Team", emoji: "🤙", english: "Team", hindi: "Team" },
  "Grandmother": { gesture: "Grandmother", emoji: "🤙", english: "Grandmother", hindi: "Grandmother" },
  "Thursday": { gesture: "Thursday", emoji: "📅", english: "Thursday", hindi: "गुरुवार" },
  "Friday": { gesture: "Friday", emoji: "📅", english: "Friday", hindi: "शुक्रवार" },
  "Husband": { gesture: "Husband", emoji: "🤙", english: "Husband", hindi: "Husband" },
  "Saturday": { gesture: "Saturday", emoji: "📅", english: "Saturday", hindi: "शनिवार" },
  "Wife": { gesture: "Wife", emoji: "🤙", english: "Wife", hindi: "Wife" },
  "King": { gesture: "King", emoji: "🤙", english: "King", hindi: "King" },
  "Today": { gesture: "Today", emoji: "📅", english: "Today", hindi: "आज" },
  "Queen": { gesture: "Queen", emoji: "🤙", english: "Queen", hindi: "Queen" },
  "Tomorrow": { gesture: "Tomorrow", emoji: "📆", english: "Tomorrow", hindi: "कल" },
  "President": { gesture: "President", emoji: "🤙", english: "President", hindi: "President" },
  "Yesterday": { gesture: "Yesterday", emoji: "🔙", english: "Yesterday", hindi: "बीता हुआ कल" },
  "Neighbour": { gesture: "Neighbour", emoji: "🤙", english: "Neighbour", hindi: "Neighbour" },
  "Week": { gesture: "Week", emoji: "📅", english: "Week", hindi: "सप्ताह" },
  "Boy": { gesture: "Boy", emoji: "👦", english: "Boy", hindi: "लड़का" },
  "Month": { gesture: "Month", emoji: "🗓️", english: "Month", hindi: "महीना" },
  "Girl": { gesture: "Girl", emoji: "👧", english: "Girl", hindi: "लड़की" },
  "Year": { gesture: "Year", emoji: "📅", english: "Year", hindi: "साल" },
  "long": { gesture: "long", emoji: "📏", english: "long", hindi: "लंबा" },
  "Child": { gesture: "Child", emoji: "🤙", english: "Child", hindi: "Child" },
  "Hour": { gesture: "Hour", emoji: "🤙", english: "Hour", hindi: "Hour" },
  "short": { gesture: "short", emoji: "🧍", english: "short", hindi: "छोटा" },
  "Animal": { gesture: "Animal", emoji: "🤙", english: "Animal", hindi: "Animal" },
  "Blind": { gesture: "Blind", emoji: "🦯", english: "Blind", hindi: "अंधा" },
  "Race (ethnicity)": { gesture: "Race (ethnicity)", emoji: "🤙", english: "Race (ethnicity)", hindi: "Race (ethnicity)" },
  "Adult": { gesture: "Adult", emoji: "🤙", english: "Adult", hindi: "Adult" },
  "Minute": { gesture: "Minute", emoji: "🤙", english: "Minute", hindi: "Minute" },
  "tall": { gesture: "tall", emoji: "🦒", english: "tall", hindi: "लंबा" },
  "Friend": { gesture: "Friend", emoji: "🤝", english: "Friend", hindi: "दोस्त" },
  "Second": { gesture: "Second", emoji: "🤙", english: "Second", hindi: "Second" },
  "wide": { gesture: "wide", emoji: "↔️", english: "wide", hindi: "चौड़ा" },
  "Morning": { gesture: "Morning", emoji: "🌅", english: "Morning", hindi: "सुबह" },
  "Player": { gesture: "Player", emoji: "🤙", english: "Player", hindi: "Player" },
  "narrow": { gesture: "narrow", emoji: "➡️", english: "narrow", hindi: "संकीर्ण" },
  "Afternoon": { gesture: "Afternoon", emoji: "☀️", english: "Afternoon", hindi: "दोपहर" },
  "Crowd": { gesture: "Crowd", emoji: "🤙", english: "Crowd", hindi: "Crowd" },
  "big large": { gesture: "big large", emoji: "🐘", english: "big large", hindi: "बड़ा" },
  "Evening": { gesture: "Evening", emoji: "🌇", english: "Evening", hindi: "शाम" },
  "Teacher": { gesture: "Teacher", emoji: "👨‍🏫", english: "Teacher", hindi: "शिक्षक" },
  "small little": { gesture: "small little", emoji: "🐜", english: "small little", hindi: "छोटा" },
  "Night": { gesture: "Night", emoji: "🌙", english: "Night", hindi: "रात" },
  "Student": { gesture: "Student", emoji: "🧑‍🎓", english: "Student", hindi: "छात्र" },
  "slow": { gesture: "slow", emoji: "🐢", english: "slow", hindi: "धीमा" },
  "Lawyer": { gesture: "Lawyer", emoji: "🤙", english: "Lawyer", hindi: "Lawyer" },
  "Time": { gesture: "Time", emoji: "⌚", english: "Time", hindi: "समय" },
  "fast": { gesture: "fast", emoji: "⚡", english: "fast", hindi: "तेज़" },
  "Doctor": { gesture: "Doctor", emoji: "👨‍⚕️", english: "Doctor", hindi: "डॉक्टर" },
  "hot": { gesture: "hot", emoji: "🔥", english: "hot", hindi: "गरम" },
  "Patient": { gesture: "Patient", emoji: "🤙", english: "Patient", hindi: "Patient" },
  "cold": { gesture: "cold", emoji: "❄️", english: "cold", hindi: "ठंडा" },
  "Waiter": { gesture: "Waiter", emoji: "🤙", english: "Waiter", hindi: "Waiter" },
  "warm": { gesture: "warm", emoji: "🌡️", english: "warm", hindi: "गर्म" },
  "Technology": { gesture: "Technology", emoji: "🤙", english: "Technology", hindi: "Technology" },
  "Train": { gesture: "Train", emoji: "🚆", english: "Train", hindi: "ट्रेन" },
  "Secretary": { gesture: "Secretary", emoji: "🤙", english: "Secretary", hindi: "Secretary" },
  "cool": { gesture: "cool", emoji: "🧊", english: "cool", hindi: "ठंडा" },
  "Priest": { gesture: "Priest", emoji: "🤙", english: "Priest", hindi: "Priest" },
  "new": { gesture: "new", emoji: "🆕", english: "new", hindi: "नया" },
  "Police": { gesture: "Police", emoji: "🤙", english: "Police", hindi: "Police" },
  "old": { gesture: "old", emoji: "🕰️", english: "old", hindi: "पुराना" },
  "Soldier": { gesture: "Soldier", emoji: "🤙", english: "Soldier", hindi: "Soldier" },
  "young": { gesture: "young", emoji: "🧒", english: "young", hindi: "युवा" },
  "Artist": { gesture: "Artist", emoji: "🤙", english: "Artist", hindi: "Artist" },
  "good": { gesture: "good", emoji: "👍", english: "good", hindi: "अच्छा" },
  "Author": { gesture: "Author", emoji: "🤙", english: "Author", hindi: "Author" },
  "bad": { gesture: "bad", emoji: "👎", english: "bad", hindi: "बुरा" },
  "Manager": { gesture: "Manager", emoji: "🤙", english: "Manager", hindi: "Manager" },
  "wet": { gesture: "wet", emoji: "💧", english: "wet", hindi: "गीला" },
  "Reporter": { gesture: "Reporter", emoji: "🤙", english: "Reporter", hindi: "Reporter" },
  "dry": { gesture: "dry", emoji: "🏜️", english: "dry", hindi: "सूखा" },
  "Actor": { gesture: "Actor", emoji: "🤙", english: "Actor", hindi: "Actor" },
  "sick": { gesture: "sick", emoji: "🤒", english: "sick", hindi: "बीमार" },
  "Job": { gesture: "Job", emoji: "🤙", english: "Job", hindi: "Job" },
  "healthy": { gesture: "healthy", emoji: "💪", english: "healthy", hindi: "स्वस्थ" },
  "Ex. Monsoon": { gesture: "Ex. Monsoon", emoji: "🤙", english: "Ex. Monsoon", hindi: "Ex. Monsoon" },
  "Extra": { gesture: "Extra", emoji: "🤙", english: "Extra", hindi: "Extra" },
}

export function getDisplayLabel(cleanLabel: string): DisplayData {
  return DISPLAY_MAP[cleanLabel] || { gesture: cleanLabel, emoji: '🤙', english: cleanLabel, hindi: cleanLabel }
}
